name: Sanity_BDD_Cucumber
on:
  #  schedule:
  #    - cron: '30 11 * * *'
    workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version
    - name: Build with Maven
      run: |
          pwd
          ls -a
          mvn clean test -DbrowserName=chrome
          ls -a
          git add screenshots
          git add Reports
          git config --global  user.email "lokeech@gmail.com"
          git config --global  user.name  "ChintaLokesh"
          git commit -m " commit reports "
          git push
